# Generated by Django 3.2.9 on 2021-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Pedido',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
